global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']
    metrics_path: '/metrics'

  - job_name: 'gateway-api'
    static_configs:
      - targets: ['gateway.api:8080']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'status-api'
    static_configs:
      - targets: ['status.api:8080']
    metrics_path: '/metrics'
    scrape_interval: 10s